---

# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: dnsutils
  - name: git
  - name: htop
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget
  - name: vim 

# ironicbadger.bash-aliases (formerly ferrarimarco.bash-aliases)
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml " }
  - { alias: "dprunesys", command: "docker system prune --all" }
  - { alias: "dtop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop" }
  - { alias: "zspace", command: "zfs list -o space" }
  - { alias: "zsnap", command: "zfs list -t snapshot" }
  - { alias: "dfclean", command: "df -h -x tmpfs -t fuse.mergerfs -t xfs -t ext4 -t zfs"}

# ironicbadger.docker_compose_generator
appdata_path: /opt/appdata
containers:
  - service_name: npm
    active: true
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

# gerrlingguy.pip 
pip_install_packages:
  - name: docker
  - name: docker-compose

# geerlingguy.ntp
ntp_timezone: America/Chicago
