---

appdata_path: /opt/appdata
containers:
  - service_name: nginx
    active: true
    image: 'nginx:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data:/data


