---
  - hosts: servers
    vars_files:
      - '../vars/vault.yaml'
    roles:
      - role: grog.package
      - role: geerlingguy.docker
      - role: ironicbadger.bash_aliases
      - role: geerlingguy.ntp
      - role: geerlingguy.pip
    tasks:
      - name: create docker-user
        ansible.builtin.user:
          name: docker-user
          shell: /bin/bash
          groups: docker,sudo
          append: yes
          password: "{{ 'password' | password_hash('sha512') }}"
          update_password: on_create
      - name: force docker-user to change password
        shell: chage -d 0 docker-user
      - name: add docker-user ssh public key
        ansible.posix.authorized_key:
          user: docker-user
          state: present
          key: "{{ lookup('file', '/home/lurch/.ssh/github.pub') }}"

