---
  - hosts: secretsvid
    vars_files:
      - '../vars/vault.yaml'
    roles:
      - role: grog.package
      - role: geerlingguy.docker
      - role: geerlingguy.pip
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.docker_compose_generator
        tags: compose
    tasks:
      - name: start docker containers
        tags: compose
        community.docker.docker_compose:
          state: present
          pull: true
          project_src: "/root"
      - name: create docker-user
        ansible.builtin.user:
          name: docker-user
          shell: /bin/bash
          groups: docker,sudo
          append: yes
