---
  - hosts: monitoring
    gather_facts: no
    tasks:
      #      - name: create dest directory
      # ansible.builtin.file:
      #   path: "{{ appdata_path}}/traefik/configuration/"
      #   state: directory
      #   mode: '0777'
      - name: copy treafik tls config
        ansible.builtin.copy:
          src: "tls.yaml"
          dest: "{{ appdata_path }}/traefik/configuration/tls.yaml"
          owner: docker-user
          group: docker
          mode: "0664"

  - hosts: servers 
    gather_facts: no
    roles:
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.docker_compose_generator
        tags: compose
    tasks:
      - name: start docker containers
        tags: compose
        community.docker.docker_compose:
          state: present
          pull: true
          project_src: "/home/docker-user"

