---
  - hosts: secretsvid
    gather_facts: no
    roles:
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.docker_compose_generator
        tags: compose
    tasks:
      - name: start docker containers
        tags: compose
        community.docker.docker_compose:
          state: present
          pull: true
          project_src: "/home/docker-user"

